trigger:
- main  

pool:
  name: default 

variables:
  nodeVersion: '18.x'
  buildDir: 'build'  # ou 'dist' se usar Vite
  destinationPath: 'C:\Users\Mateus\Desktop\PublishWeb' 

steps:
- task: NodeTool@0
  displayName: 'Instalar Node.js'
  inputs:
    versionSpec: '$(nodeVersion)'
    checkLatest: true

- script: |
    npm install
  displayName: 'Instalar dependências'

- script: |
    npm run build
  displayName: 'Executar build do React'

- powershell: |
    $source = "$(System.DefaultWorkingDirectory)\$(buildDir)"
    $destination = "$(destinationPath)"

    if (!(Test-Path -Path $destination)) {
      New-Item -ItemType Directory -Path $destination | Out-Null
    }

    Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force

    Write-Host "Build do React copiado com sucesso para: $destination"
  displayName: 'Copiar build para IIS'
